name: Build, Zip, and Deploy via FTP

on:
  push:
    branches: [ "publish" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # ===================================================================
    # STEP 1-5: Build, package, and prepare all files locally first.
    # ===================================================================
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish Portable App
      run: dotnet publish --configuration Release --runtime win-x64 --output ./publish -p:PublishSingleFile=true --self-contained true

    - name: List files in publish directory (before removal)
      run: ls -R ./publish

    - name: Remove User-Specific Files
      run: |
        rm ./publish/Data/clients.json
        rm ./publish/Data/personnel.json
        rm ./publish/Data/settings.json
      shell: bash

    - name: List files in publish directory (after removal)
      run: ls -R ./publish

    - name: Zip the release
      uses: thejoshwolfe/zip-release-action@v1
      with:
        filename: 'FAST-PDF_latest.zip'
        directory: './publish'
        path: '.'

    # ===================================================================
    # STEP 6-8: Prepare the version.txt file locally.
    # ===================================================================
    - name: Read .csproj
      id: read_project
      uses: CumulusDS/read-file-action@v1
      with:
        path: './FAST-PDF.csproj'

    - name: Extract Project Version
      id: extract_version
      uses: 'regex-match@v2'
      with:
        text: ${{ steps.read_project.outputs.content }}
        regex: '(?<=<AssemblyVersion>).*(?=</AssemblyVersion>)'

    - name: Create version.txt for deployment
      run: echo "${{ steps.extract_version.outputs.match }}" > version.txt

    # DEBUG: Show the content of all files about to be deployed
    - name: List final files in root directory
      run: ls -l

    - name: Show final version.txt content
      run: cat version.txt

    # ===================================================================
    # STEP 9-10: All local operations are done. Begin deployment to server.
    # ===================================================================
    - name: Deploy Application ZIP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /fast.shahafshavit.com/updates/ # Make sure this server path is correct
        include: |
          FAST-PDF_latest.zip
        log-level: "verbose"

    - name: Deploy version.txt
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /fast.shahafshavit.com/updates/ # Make sure this server path is correct
        include: |
          version.txt
        state-name: ftp-state-version.json
        log-level: "verbose"